@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/api/auth/login

###
GET {{baseUrl}}/api/auth/register

###
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "fuckyou@gmail.com"
}


###
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "eMartinez",
  "email": "fuckyou@gmail.com",
  "password": "emi123"
}